module

public import WeilClasses.Main.Coordinates
public import WeilClasses.PureSpinor.CM

/-!
# The abelian variety `X × X̂` of Weil type of Theorems 1.4.1 and 1.5.1, explicitly

For an abelian `n`-fold `X` with principal polarization `Θ = e₁ ∧ e₂ + ⋯ + e_{2n-1} ∧ e_{2n}`
(`ThetaStd`; for `n = 3`, the Jacobian of a genus-3 curve) and `d > 0`, the paper equips `X × X̂` with
the structure of a polarized abelian `2n`-fold of Weil type for `K = ℚ(√-d)` (§2.4, Lemma 3.1.3,
Corollary 3.2.3), from the `K`-secant spanned by the pure spinors `exp(±√-d Θ)`. In coordinates
(`V = H¹(X̂) ⊕ H¹(X)`, pairs `(y, w)`), with `θ : H¹(X)* → H¹(X)` the contraction with `Θ`
((2.4.3); `θ(f_{2i}) = e_{2i+1}`, `θ(f_{2i+1}) = -e_{2i}`):

* `η(√-d) = f`, `f(y, w) = (-θ⁻¹(w), d θ(y))` (`WeilClasses.fV`), so `η(a + b√-d) = a + b f`
  (`WeilClasses.etaV`); this is the paper's `η` of (2.2.4) for the secant `P_Θ` (compared in
  `WeilClasses.Main.Compare`);
* the polarization `h = d Θ + Θ̂ ∈ H²(X × X̂, ℚ)`, `Θ̂ = f₁ ∧ f₂ + ⋯ + f_{2n-1} ∧ f_{2n}`
  (`WeilClasses.hV`): the class of the paper's `Ξ_P` (2.4.2) under `V ≅ V*`;
* the complex structure of `X × X̂` given by a complex structure `J` of `H¹(X, ℝ)`: in the standard
  convention (`H^{1,0}` the `i`-eigenspace) it is `(y, w) ↦ (-y ∘ J, J w)` (`WeilClasses.stdStructure`),
  the negative of the paper's `I_{V_ℝ}` (`productStructure`).

`fX`, `hX`, `JX` are their transports to the model (`H¹ = ℚ^{4n}`, `coordV`). The data `fV`, `hV`,
`stdStructure`, `fX`, `hX`, `JX` are defined in `WeilClasses.Defs` (they enter the statements of
record); this file defines the action `η` itself (`etaV`, `etaX`), which the statements of record
quantify over (`η` with `η(√-d) = f`; it is unique, `eq_etaX`).
-/

@[expose] public section

namespace WeilClasses

variable (n : ℕ)

/-- `f² = -d`. -/
theorem fV_mul_self (d : ℚ) : fV n d * fV n d = -(d • 1) := by
  sorry

/-- The action `η : K → End_ℚ(V_ℚ)` of `K = ℚ(√-d)` on `H¹(X × X̂, ℚ)`: `η(a + b√-d) = a + b f`. -/
noncomputable def etaV (d : ℚ) (hd : 0 < d) : Kd d →+* Module.End ℚ (V ℚ n) where
  toFun k := Kd.ratPart d k • 1 + Kd.sqrtNegCoeff d k • fV n d
  map_one' := by sorry
  map_mul' := by sorry
  map_zero' := by sorry
  map_add' := by sorry

/-! ## Transport to the model `H¹ = ℚ^{4n}` -/

/-- `η` on the model `H¹(X × X̂, ℚ) = ℚ^{4n}`. -/
noncomputable def etaX (d : ℚ) (hd : 0 < d) : Kd d →+* Module.End ℚ (H1 ℚ (2 * n)) :=
  ((coordV ℚ n).conjAlgEquiv ℚ).toRingHom.comp (etaV n d hd)

/-- `η(√-d) = f` in the model. -/
theorem etaX_sqrtNeg (d : ℚ) (hd : 0 < d) : etaX n d hd (Kd.sqrtNeg d) = fX n d := by
  sorry

/-- The action of `K` with `η(√-d) = f` is unique (`K = ℚ(√-d)` is generated by `√-d`). -/
theorem eq_etaX (d : ℚ) (hd : 0 < d) (η : Kd d →+* Module.End ℚ (H1 ℚ (2 * n)))
    (hη : η (Kd.sqrtNeg d) = fX n d) : η = etaX n d hd := by
  sorry

end WeilClasses
