module

public import WeilClasses.PureSpinor.Stabilizer
public import WeilClasses.PureSpinor.Lemma2_2_4
public import WeilClasses.PureSpinor.Lemma2_2_6

/-!
# Weight decompositions of `⋀• V` and Lemma 2.2.7 (paper §2.2, end)

Setting: a rational `K`-secant `P` (`WeilClasses.KSecant`) which is non-isotropic, so that
`V_K = W₁ ⊕ W₂` and `K` acts on `V_ℚ` by `η` (2.2.4).

## Main definitions

* `WeilClasses.pqPiece A B p q`: the subspace `⋀^p A ∧ ⋀^q B ⊆ ⋀^{p+q} M` spanned by products of
  `p` vectors of `A` and `q` vectors of `B` (the foundation's `pqPiece`, over any field); for
  `A = W₁`, `B = W₂` this is the paper's `⋀^p W₁ ⊗ ⋀^q W₂`.
* `WeilClasses.weightSpaceK d act a b`: for an action `λ ↦ act λ` of `K^×` on a `K`-vector space `U`
  (the paper's `U_K = U ⊗_ℚ K`, with the `K`-linear extension of the action), the subspace
  `U_{a,b}` on which `λ` acts by `λ^a σ(λ)^b`.
* `KSecant.ηExt`: the action `⋀ η_λ` of `λ ∈ K` on `⋀• V_K`; `KSecant.wedgeAB`:
  `⋀_{a,b} V := (⋀^{a+b} V)_{a,b}`; `KSecant.wedgePQAB`: `⋀^{p,q}_{a,b} V ⊆ ⋀^{p+q} V_ℂ` (Hodge type
  `(p, q)` for the complex structure of `X × X̂`, `K`-weight `(a, b)`).
* `KSecant.spinPZ`: the integral group `Spin(V)_P` of (2.2.2), i.e. `SpinZ n ⊓ Spin(V_ℚ)_P`.
* `WeilClasses.invariantsExt F n H`: the vectors of `⋀• V_F` fixed by a subgroup `H ⊆ Spin(V_F)`
  (acting by `ρ`, preserving the grading); `KSecant.invQ k = (⋀^k V_ℚ)^{Spin(V)_P}` and
  `KSecant.invK k = (⋀^k V_K)^{Spin(V)_P}`.

## Statements

* The claims between Lemma 2.2.6 and Lemma 2.2.7: `KSecant.weightSpaceK_ηK_one_zero`,
  `KSecant.weightSpaceK_ηK_zero_one` (`W₁ = V_{1,0}`, `W₂ = V_{0,1}`), `KSecant.wedgeAB_eq`
  (`⋀_{a,b} V = ⋀^a W₁ ⊗ ⋀^b W₂`), `KSecant.conjExt_mem_wedgeAB` (`U_{a,b} ⊕ U_{b,a}` is defined
  over `ℚ`), `KSecant.wedge_decomp` (`⋀^k V_K = ⊕_{a+b=k} ⋀^a W₁ ⊗ ⋀^b W₂`),
  `KSecant.wedgePQAB_decomp` (`⋀^k V_ℂ = ⊕ ⋀^{p,q}_{a,b} V`), `KSecant.map_ι_W₁ℂ_V10` (and three
  more: `W₁^{1,0} = ⋀^{1,0}_{1,0}V`, etc.).
* **Lemma 2.2.7**: `lemma2_2_7_hodge` (the invariants are of Hodge type), `lemma2_2_7_odd`,
  `lemma2_2_7_even`, `lemma2_2_7_middle` (the dimensions `0`, `1`, `3`), `lemma2_2_7_K_*` (the
  decomposition of `(⋀^{2n} V_K)^{Spin(V)_P}` into the characters `det₁`, `det₂`, `1` of
  `Spin(V_K)_{ℓ₁,ℓ₂}`), `lemma2_2_7_trivial` (for `j ≠ n` the invariant line is a trivial
  character), the irreducibility used in the proof (`lemma2_2_7_irreducible₁`,
  `lemma2_2_7_irreducible₂`), and the note after the lemma (`lemma2_2_7_note`,
  `lemma2_2_7_note_pow`: the invariants are the powers of a non-degenerate invariant `2`-form, apart
  from the Hodge–Weil plane in degree `2n`).
* `eq_of_character_eq`: the characters `λ ↦ λ^a σ(λ)^b` of `K^×` are pairwise distinct (the paper's
  "`Hom(K^×, K^×) ≅ ℤ × ℤ`").

## Note for the proofs

The group of Lemma 2.2.7 is the *integral* group `Spin(V)_P` of (2.2.2), acting on `⋀• V_ℚ` through
`ρ` (`WeilClasses.rhoExt`), as printed. The paper's proof uses, without proof, that `⋀^k Wᵢ`
(`0 ≤ k ≤ 2n`) is an irreducible representation of `Spin(V)_P`. This holds for the algebraic group
`Spin(V_K)_P ≅ SL(W₁)`; for the integral group it needs a density argument (`Spin(V)_P` is an
arithmetic subgroup of a `ℚ`-form of `SL_{2n}` with noncompact real points, hence Zariski dense by
Borel's density theorem; or an argument with unipotent elements `1 + t N`, `t ∈ ℤ`).
-/

@[expose] public section

namespace WeilClasses

open CliffordAlgebra

/-! ## Products of exterior powers of two subspaces -/

section Pieces

variable (F : Type*) [Field F] {M : Type*} [AddCommGroup M] [Module F M]

end Pieces

/-! ## Weight spaces of an action of `K^×` -/

section Weight

variable (d : ℚ) {U : Type*} [AddCommGroup U] [Module (Kd d) U]

/-- "**The character group `Hom(K^×, K^×)` is isomorphic to `ℤ × ℤ`, generated by `id` and
conjugation**" (§2.2, before Lemma 2.2.7). Reading: the algebraic characters of the torus
`R_{K/ℚ} 𝔾_m` over `K` (algebraic groups are not modeled; as abstract groups `Hom(K^×, K^×)` is much
larger). We state the part used for the weight decompositions: the characters
`λ ↦ λ^a σ(λ)^b`, `(a, b) ∈ ℤ²`, are pairwise distinct on `K^×`. -/
theorem eq_of_character_eq (hd : 0 < d) (a b a' b' : ℤ)
    (h : ∀ l : Kd d, l ≠ 0 → l ^ a * Kd.σ d l ^ b = l ^ a' * Kd.σ d l ^ b') :
    a = a' ∧ b = b' := by
  sorry

/-- The weight space `U_{a,b}` (§2.2, before Lemma 2.2.7): given a `ℚ`-vector space with an action
of `K^×`, the subspace of `U_K = U ⊗_ℚ K` on which `λ ∈ K^×` acts by `λ^a σ(λ)^b`. Here `U` is the
`K`-vector space `U_K` and `act λ` the `K`-linear extension of the action of `λ`. -/
def weightSpaceK (act : Kd d → Module.End (Kd d) U) (a b : ℤ) : Submodule (Kd d) U where
  carrier := {x | ∀ l : Kd d, l ≠ 0 → act l x = (l ^ a * Kd.σ d l ^ b) • x}
  add_mem' := by
    intro x y hx hy l hl
    rw [map_add, hx l hl, hy l hl, smul_add]
  zero_mem' := by
    intro l _
    rw [map_zero, smul_zero]
  smul_mem' := by
    intro c x hx l hl
    rw [map_smul, hx l hl, smul_comm]

end Weight

/-! ## Invariants of a subgroup of `Spin(V_F)` in `⋀• V_F` -/

section Invariants

variable (F : Type*) [Field F] [CharZero F] (n : ℕ)

/-- The vectors of `⋀• V_F = H*(X × X̂, F)` fixed by every element of a subgroup `H ⊆ Spin(V_F)`,
acting by `ρ_g = ⋀• ρ(g)` (the action of Diagram (1.3.1) preserving the grading). -/
def invariantsExt (H : Subgroup (Spin F n)) : Submodule F (ExteriorAlgebra F (V F n)) where
  carrier := {α | ∀ g ∈ H, rhoExt F n g α = α}
  add_mem' := by
    intro x y hx hy g hg
    rw [map_add, hx g hg, hy g hg]
  zero_mem' := by
    intro g _
    rw [map_zero]
  smul_mem' := by
    intro c x hx g hg
    rw [map_smul, hx g hg]

end Invariants

namespace KSecant

variable {n : ℕ} {d : ℚ} (P : KSecant n d)

/-! ## The `K`-weight decomposition of `⋀• V_K` -/

/-- The action `⋀ η_λ` of `λ ∈ K` on `⋀• V_K` induced by (2.2.4). -/
noncomputable def ηExt (hW : IsCompl P.W₁ P.W₂) (l : Kd d) :
    Module.End (Kd d) (ExteriorAlgebra (Kd d) (V (Kd d) n)) :=
  (ExteriorAlgebra.map (P.ηK hW l)).toLinearMap

/-- `⋀_{a,b} V := (⋀^{a+b} V)_{a,b}` (§2.2, before Lemma 2.2.7): the vectors of `⋀^{a+b} V_K` on
which `λ ∈ K^×` acts by `λ^a σ(λ)^b`. -/
noncomputable def wedgeAB (hW : IsCompl P.W₁ P.W₂) (a b : ℕ) :
    Submodule (Kd d) (ExteriorAlgebra (Kd d) (V (Kd d) n)) :=
  ⋀[Kd d]^(a + b) (V (Kd d) n) ⊓ weightSpaceK d (P.ηExt hW) a b

/-- "**`W₁ = V_{1,0}`**" (§2.2): `W₁` is the subspace of `V_K` on which `λ` acts by `λ`. -/
theorem weightSpaceK_ηK_one_zero (hd : 0 < d) (hW : IsCompl P.W₁ P.W₂) :
    weightSpaceK d (P.ηK hW) 1 0 = P.W₁ := by
  sorry

/-- "**`W₂ = V_{0,1}`**" (§2.2): `W₂` is the subspace of `V_K` on which `λ` acts by `σ(λ)`. -/
theorem weightSpaceK_ηK_zero_one (hd : 0 < d) (hW : IsCompl P.W₁ P.W₂) :
    weightSpaceK d (P.ηK hW) 0 1 = P.W₂ := by
  sorry

/-- "**`⋀_{a,b} V = ⋀^a W₁ ⊗ ⋀^b W₂`**" (§2.2). -/
theorem wedgeAB_eq (hd : 0 < d) (hW : IsCompl P.W₁ P.W₂) (a b : ℕ) :
    P.wedgeAB hW a b = pqPiece P.W₁ P.W₂ a b := by
  sorry

/-- "**The subspaces `U_{a,b} ⊕ U_{b,a}` are defined over `ℚ`**" (§2.2), for `U = ⋀• V`: the Galois
involution `σ` maps `⋀_{a,b} V` to `⋀_{b,a} V`. -/
theorem conjExt_mem_wedgeAB (hd : 0 < d) (hW : IsCompl P.W₁ P.W₂) (a b : ℕ)
    (x : ExteriorAlgebra (Kd d) (V (Kd d) n)) (hx : x ∈ P.wedgeAB hW a b) :
    conjExt (Kd.σ d) n x ∈ P.wedgeAB hW b a := by
  sorry

/-- "**`⋀^k V_K ≅ ⊕_{a+b=k} (⋀^a W₁) ⊗ (⋀^b W₂)`**" (proof of Lemma 2.2.7): `⋀^k V_K` is the
internal direct sum of the subspaces `⋀^a W₁ ∧ ⋀^{k-a} W₂`, `0 ≤ a ≤ k`. -/
theorem wedge_decomp (hd : 0 < d) (hW : IsCompl P.W₁ P.W₂) (k : ℕ) :
    iSupIndep (fun a : Fin (k + 1) => pqPiece P.W₁ P.W₂ a (k - a)) ∧
      ⨆ a : Fin (k + 1), pqPiece P.W₁ P.W₂ a (k - a) = ⋀[Kd d]^k (V (Kd d) n) := by
  sorry

/-- `⋀^{p,q}_{a,b} V ⊆ ⋀^{p+q} V_ℂ` (§2.2, before Lemma 2.2.7): the vectors of Hodge type `(p, q)`
for the complex structure `I` (the `ℂ^×`-action `x + iy ↦ x + y I`) and of `K`-weight `(a, b)`. -/
noncomputable def wedgePQAB (hW : IsCompl P.W₁ P.W₂) (I : Module.End ℝ (V ℝ n)) (p q a b : ℕ) :
    Submodule ℂ (ExteriorAlgebra ℂ (V ℂ n)) :=
  pqPiece (V10 n I) (V01 n I) p q ⊓
    Submodule.span ℂ
      (bcExt (Kd d) ℂ n '' (P.wedgeAB hW a b : Set (ExteriorAlgebra (Kd d) (V (Kd d) n))))

/-- "**`⋀^k V_ℂ = ⊕_{p+q=k, a+b=k} ⋀^{p,q}_{a,b} V`**" (§2.2): the actions of `K^×` and of `ℂ^×`
on `⋀• V_ℂ` commute (this uses that `P` is contained in the Hodge ring, through Lemma 2.2.6), and
`⋀^k V_ℂ` is the direct sum of their joint weight spaces. -/
theorem wedgePQAB_decomp (hd : 0 < d) (hP : ¬ P.IsIsotropic) (J : Module.End ℝ (H1 ℝ n))
    (hJ : IsComplexStructure J) (hPJ : P.Pℚ ≤ hodgeRingX n J) (k : ℕ) :
    iSupIndep (fun pa : Fin (k + 1) × Fin (k + 1) =>
        P.wedgePQAB (P.isCompl_of_not_isIsotropic hd hP) (productStructure n J)
          pa.1 (k - pa.1) pa.2 (k - pa.2)) ∧
      ⨆ pa : Fin (k + 1) × Fin (k + 1),
          P.wedgePQAB (P.isCompl_of_not_isIsotropic hd hP) (productStructure n J)
            pa.1 (k - pa.1) pa.2 (k - pa.2) = ⋀[ℂ]^k (V ℂ n) := by
  sorry

/-- "**`W₁^{1,0} = ⋀^{1,0}_{1,0} V`**" (§2.2), under the hypotheses of Lemma 2.2.6. -/
theorem map_ι_W₁ℂ_V10 (hd : 0 < d) (hP : ¬ P.IsIsotropic) (J : Module.End ℝ (H1 ℝ n))
    (hJ : IsComplexStructure J) (hPJ : P.Pℚ ≤ hodgeRingX n J) :
    (P.W₁ℂ ⊓ V10 n (productStructure n J)).map (ExteriorAlgebra.ι ℂ) =
      P.wedgePQAB (P.isCompl_of_not_isIsotropic hd hP) (productStructure n J) 1 0 1 0 := by
  sorry

/-- "**`W₁^{0,1} = ⋀^{0,1}_{1,0} V`**" (§2.2). -/
theorem map_ι_W₁ℂ_V01 (hd : 0 < d) (hP : ¬ P.IsIsotropic) (J : Module.End ℝ (H1 ℝ n))
    (hJ : IsComplexStructure J) (hPJ : P.Pℚ ≤ hodgeRingX n J) :
    (P.W₁ℂ ⊓ V01 n (productStructure n J)).map (ExteriorAlgebra.ι ℂ) =
      P.wedgePQAB (P.isCompl_of_not_isIsotropic hd hP) (productStructure n J) 0 1 1 0 := by
  sorry

/-- "**`W₂^{1,0} = ⋀^{1,0}_{0,1} V`**" (§2.2). -/
theorem map_ι_W₂ℂ_V10 (hd : 0 < d) (hP : ¬ P.IsIsotropic) (J : Module.End ℝ (H1 ℝ n))
    (hJ : IsComplexStructure J) (hPJ : P.Pℚ ≤ hodgeRingX n J) :
    (P.W₂ℂ ⊓ V10 n (productStructure n J)).map (ExteriorAlgebra.ι ℂ) =
      P.wedgePQAB (P.isCompl_of_not_isIsotropic hd hP) (productStructure n J) 1 0 0 1 := by
  sorry

/-- "**`W₂^{0,1} = ⋀^{0,1}_{0,1} V`**" (§2.2). -/
theorem map_ι_W₂ℂ_V01 (hd : 0 < d) (hP : ¬ P.IsIsotropic) (J : Module.End ℝ (H1 ℝ n))
    (hJ : IsComplexStructure J) (hPJ : P.Pℚ ≤ hodgeRingX n J) :
    (P.W₂ℂ ⊓ V01 n (productStructure n J)).map (ExteriorAlgebra.ι ℂ) =
      P.wedgePQAB (P.isCompl_of_not_isIsotropic hd hP) (productStructure n J) 0 1 0 1 := by
  sorry

/-! ## The integral group `Spin(V)_P` and its invariants -/

/-- `(⋀^k V_ℚ)^{Spin(V)_P}`: the `Spin(V)_P`-invariant rational classes of degree `k` on
`X × X̂`. -/
noncomputable def invQ (k : ℕ) : Submodule ℚ (ExteriorAlgebra ℚ (V ℚ n)) :=
  ⋀[ℚ]^k (V ℚ n) ⊓ invariantsExt ℚ n P.spinPZ

/-- `(⋀^k V_K)^{Spin(V)_P}`: the vectors of `⋀^k V_K` invariant under the integral group
`Spin(V)_P`, acting through `Spin(V) ⊆ Spin(V_ℚ) → Spin(V_K)`. -/
noncomputable def invK (k : ℕ) : Submodule (Kd d) (ExteriorAlgebra (Kd d) (V (Kd d) n)) :=
  ⋀[Kd d]^k (V (Kd d) n) ⊓ invariantsExt (Kd d) n (P.spinPZ.map (bcSpin ℚ (Kd d) n))

/-! ## Lemma 2.2.7 -/

/-- **Lemma 2.2.7** (`lemma-Spin-V-P-invariant-classes-are-Hodge`), first sentence: the
`Spin(V)_P`-invariant subspace `(⋀^{2j} V_ℚ)^{Spin(V)_P}` is a subspace of `⋀^{j,j} V_ℂ`, i.e. it
consists of Hodge classes for the complex structure of `X × X̂`. Reading: as in Lemma 2.2.6 (whose
conclusion the proof uses), `P` is contained in the Hodge ring of `X` for the complex structure `J`
of `X`; without this the statement is false. Group: the integral `Spin(V)_P` (see the module
docstring). -/
theorem _root_.WeilClasses.lemma2_2_7_hodge (hd : 0 < d) (hP : ¬ P.IsIsotropic)
    (J : Module.End ℝ (H1 ℝ n)) (hJ : IsComplexStructure J) (hPJ : P.Pℚ ≤ hodgeRingX n J)
    (j : ℕ) :
    P.invQ (2 * j) ≤ hodgeClassesV n (productStructure n J) j := by
  sorry

/-- **Lemma 2.2.7** (`lemma-Spin-V-P-invariant-classes-are-Hodge`), dimensions, `k` odd:
`dim (⋀^k V_ℚ)^{Spin(V)_P} = 0`. -/
theorem _root_.WeilClasses.lemma2_2_7_odd (hd : 0 < d) (hP : ¬ P.IsIsotropic) (k : ℕ)
    (hk : Odd k) :
    Module.finrank ℚ (P.invQ k) = 0 := by
  sorry

/-- **Lemma 2.2.7** (`lemma-Spin-V-P-invariant-classes-are-Hodge`), dimensions, `k` even:
`dim (⋀^k V_ℚ)^{Spin(V)_P} = 1` if `0 ≤ k ≤ 4n`, `k` even, `k ≠ 2n`. -/
theorem _root_.WeilClasses.lemma2_2_7_even (hd : 0 < d) (hP : ¬ P.IsIsotropic) (k : ℕ)
    (hk : Even k) (hk4 : k ≤ 4 * n) (hk2 : k ≠ 2 * n) :
    Module.finrank ℚ (P.invQ k) = 1 := by
  sorry

/-- **Lemma 2.2.7** (`lemma-Spin-V-P-invariant-classes-are-Hodge`), dimensions, middle degree:
`dim (⋀^{2n} V_ℚ)^{Spin(V)_P} = 3`. -/
theorem _root_.WeilClasses.lemma2_2_7_middle (hd : 0 < d) (hP : ¬ P.IsIsotropic) :
    Module.finrank ℚ (P.invQ (2 * n)) = 3 := by
  sorry

/-- **Lemma 2.2.7** (`lemma-Spin-V-P-invariant-classes-are-Hodge`), third sentence, the sum:
`(⋀^{2n} V_K)^{Spin(V)_P} = ⋀^{2n} W₁ ⊕ ⋀^{2n} W₂ ⊕ L`, where the trivial line is
`L = (⋀^n W₁ ⊗ ⋀^n W₂)^{Spin(V)_P}` (proof of Lemma 2.2.7). -/
theorem _root_.WeilClasses.lemma2_2_7_K_eq (hd : 0 < d) (hP : ¬ P.IsIsotropic) :
    P.invK (2 * n) =
      pqPiece P.W₁ P.W₂ (2 * n) 0 ⊔ pqPiece P.W₁ P.W₂ 0 (2 * n) ⊔
        (P.invK (2 * n) ⊓ pqPiece P.W₁ P.W₂ n n) := by
  sorry

/-- **Lemma 2.2.7** (`lemma-Spin-V-P-invariant-classes-are-Hodge`), third sentence: the sum
`⋀^{2n} W₁ + ⋀^{2n} W₂ + L` is direct. -/
theorem _root_.WeilClasses.lemma2_2_7_K_indep (hd : 0 < d) (hP : ¬ P.IsIsotropic) :
    iSupIndep ![pqPiece P.W₁ P.W₂ (2 * n) 0, pqPiece P.W₁ P.W₂ 0 (2 * n),
      P.invK (2 * n) ⊓ pqPiece P.W₁ P.W₂ n n] := by
  sorry

/-- **Lemma 2.2.7** (`lemma-Spin-V-P-invariant-classes-are-Hodge`), third sentence: the three
summands `⋀^{2n} W₁`, `⋀^{2n} W₂` and `L = (⋀^n W₁ ⊗ ⋀^n W₂)^{Spin(V)_P}` are lines. -/
theorem _root_.WeilClasses.lemma2_2_7_K_finrank (hd : 0 < d) (hP : ¬ P.IsIsotropic) :
    Module.finrank (Kd d) (pqPiece P.W₁ P.W₂ (2 * n) 0) = 1 ∧
      Module.finrank (Kd d) (pqPiece P.W₁ P.W₂ 0 (2 * n)) = 1 ∧
      Module.finrank (Kd d) (P.invK (2 * n) ⊓ pqPiece P.W₁ P.W₂ n n :
        Submodule (Kd d) (ExteriorAlgebra (Kd d) (V (Kd d) n))) = 1 := by
  sorry

/-- **Lemma 2.2.7** (`lemma-Spin-V-P-invariant-classes-are-Hodge`), third sentence: `⋀^{2n} W₁` is
the character `det₁` of `Spin(V_K)_{ℓ₁,ℓ₂}`. -/
theorem _root_.WeilClasses.lemma2_2_7_K_det₁ (hd : 0 < d) (hP : ¬ P.IsIsotropic)
    (g : P.spinL₁L₂) (x : ExteriorAlgebra (Kd d) (V (Kd d) n))
    (hx : x ∈ pqPiece P.W₁ P.W₂ (2 * n) 0) :
    rhoExt (Kd d) n g x = P.det₁ g • x := by
  sorry

/-- **Lemma 2.2.7** (`lemma-Spin-V-P-invariant-classes-are-Hodge`), third sentence: `⋀^{2n} W₂` is
the character `det₂` of `Spin(V_K)_{ℓ₁,ℓ₂}`. -/
theorem _root_.WeilClasses.lemma2_2_7_K_det₂ (hd : 0 < d) (hP : ¬ P.IsIsotropic)
    (g : P.spinL₁L₂) (x : ExteriorAlgebra (Kd d) (V (Kd d) n))
    (hx : x ∈ pqPiece P.W₁ P.W₂ 0 (2 * n)) :
    rhoExt (Kd d) n g x = P.det₂ g • x := by
  sorry

/-- **Lemma 2.2.7** (`lemma-Spin-V-P-invariant-classes-are-Hodge`), third sentence: the third
summand `L = (⋀^n W₁ ⊗ ⋀^n W₂)^{Spin(V)_P}` is the trivial character of `Spin(V_K)_{ℓ₁,ℓ₂}`. -/
theorem _root_.WeilClasses.lemma2_2_7_K_trivial (hd : 0 < d) (hP : ¬ P.IsIsotropic)
    (g : P.spinL₁L₂) (x : ExteriorAlgebra (Kd d) (V (Kd d) n))
    (hx : x ∈ P.invK (2 * n) ⊓ pqPiece P.W₁ P.W₂ n n) :
    rhoExt (Kd d) n g x = x := by
  sorry

/-- **Lemma 2.2.7** (`lemma-Spin-V-P-invariant-classes-are-Hodge`), last sentence: for `j ≠ n`,
`0 ≤ j ≤ 2n`, the space `(⋀^{2j} V_ℚ)^{Spin(V)_P}` is a trivial character of
`Spin(V_K)_{ℓ₁,ℓ₂}`. -/
theorem _root_.WeilClasses.lemma2_2_7_trivial (hd : 0 < d) (hP : ¬ P.IsIsotropic) (j : ℕ)
    (hj : j ≠ n) (hj2 : j ≤ 2 * n) (α : ExteriorAlgebra ℚ (V ℚ n)) (hα : α ∈ P.invQ (2 * j))
    (g : P.spinL₁L₂) :
    rhoExt (Kd d) n g (bcExt ℚ (Kd d) n α) = bcExt ℚ (Kd d) n α := by
  sorry

/-- Claim in the proof of Lemma 2.2.7 (`lemma-Spin-V-P-invariant-classes-are-Hodge`), stated there
without proof: for `0 ≤ k ≤ 2n`, `⋀^k W₁` is an irreducible representation of the integral group
`Spin(V)_P`. True for the algebraic group `Spin(V_K)_P ≅ SL(W₁)`; for `Spin(V)_P` it needs a density
argument (see the module docstring). -/
theorem _root_.WeilClasses.lemma2_2_7_irreducible₁ (hd : 0 < d) (hP : ¬ P.IsIsotropic) (k : ℕ)
    (hk : k ≤ 2 * n) (N : Submodule (Kd d) (ExteriorAlgebra (Kd d) (V (Kd d) n)))
    (hN : N ≤ pqPiece P.W₁ P.W₂ k 0)
    (hinv : ∀ g ∈ P.spinPZ, ∀ x ∈ N, rhoExt (Kd d) n (bcSpin ℚ (Kd d) n g) x ∈ N) :
    N = ⊥ ∨ N = pqPiece P.W₁ P.W₂ k 0 := by
  sorry

/-- Claim in the proof of Lemma 2.2.7: for `0 ≤ k ≤ 2n`, `⋀^k W₂` is an irreducible representation
of the integral group `Spin(V)_P` (see `lemma2_2_7_irreducible₁`). -/
theorem _root_.WeilClasses.lemma2_2_7_irreducible₂ (hd : 0 < d) (hP : ¬ P.IsIsotropic) (k : ℕ)
    (hk : k ≤ 2 * n) (N : Submodule (Kd d) (ExteriorAlgebra (Kd d) (V (Kd d) n)))
    (hN : N ≤ pqPiece P.W₁ P.W₂ 0 k)
    (hinv : ∀ g ∈ P.spinPZ, ∀ x ∈ N, rhoExt (Kd d) n (bcSpin ℚ (Kd d) n g) x ∈ N) :
    N = ⊥ ∨ N = pqPiece P.W₁ P.W₂ 0 k := by
  sorry

/-- The note after Lemma 2.2.7 (`lemma-Spin-V-P-invariant-classes-are-Hodge`): "the space
`(⋀² V_ℚ)^{Spin(V)_P}` is spanned by a non-degenerate `2`-form on `V_K^*`, and so the subspace
`(⋀• V_K)^{Spin(V_K)_{ℓ₁,ℓ₂}}` consists of powers of this `2`-form". For a nonzero invariant
`ω ∈ ⋀² V_ℚ`: `ω^{2n} ≠ 0` (non-degenerate), and the `Spin(V_K)_{ℓ₁,ℓ₂}`-invariants of `⋀• V_K` are
spanned by the powers of `ω`. Needs `n ≥ 2` (for `n = 1`, `(⋀² V_ℚ)^{Spin(V)_P}` is the
three-dimensional middle degree); this is the paper's standing hypothesis. -/
theorem _root_.WeilClasses.lemma2_2_7_note (hd : 0 < d) (hn : 2 ≤ n) (hP : ¬ P.IsIsotropic)
    (ω : ExteriorAlgebra ℚ (V ℚ n)) (hω : ω ∈ P.invQ 2) (hω0 : ω ≠ 0) :
    ω ^ (2 * n) ≠ 0 ∧
      invariantsExt (Kd d) n P.spinL₁L₂ =
        Submodule.span (Kd d) (Set.range fun j : ℕ => bcExt ℚ (Kd d) n ω ^ j) := by
  sorry

/-- Consequence of Lemma 2.2.7 and the note after it, used in the proof of Corollary 4.0.4 ("the
space of powers of classes in the one-dimensional `⋀²(V_ℚ)^{Spin(V)_P}`"): for `n ≥ 2`, a nonzero
invariant `ω ∈ ⋀² V_ℚ`, and `j ≠ n`, `0 ≤ j ≤ 2n`, the invariants `(⋀^{2j} V_ℚ)^{Spin(V)_P}` are
spanned by `ω^j`. -/
theorem _root_.WeilClasses.lemma2_2_7_note_pow (hd : 0 < d) (hn : 2 ≤ n) (hP : ¬ P.IsIsotropic)
    (ω : ExteriorAlgebra ℚ (V ℚ n)) (hω : ω ∈ P.invQ 2) (hω0 : ω ≠ 0) (j : ℕ) (hj : j ≠ n)
    (hj2 : j ≤ 2 * n) :
    P.invQ (2 * j) = Submodule.span ℚ {ω ^ j} := by
  sorry

end KSecant

end WeilClasses
