module

public import WeilClasses.Spinor.Embeddings
public import WeilClasses.PureSpinor.Lemma2_2_1
public import WeilClasses.Hodge.Defs

/-!
# Remark 2.2.5, Chevalley's isomorphism `φ` (2.2.5), and Lemma 2.2.6 (paper §2.2)

Let `J` be a complex structure on `H¹(X, ℝ)` (the complex structure of `X`, with
`H^{1,0}(X) = i`-eigenspace) and `I = productStructure n J` the induced complex structure of
`X × X̂` on `V_ℝ`; `V^{1,0} = V10 n I`, `V^{0,1} = V01 n I` (`WeilClasses.Hodge.Defs`). The Hodge
ring of `X` is `hodgeRingX n J`.

## Main definitions

* `KSecant.W₁ℂ`, `KSecant.W₂ℂ`: the complexifications `W_{i,ℂ}` of `W₁, W₂ ⊆ V_K`.
* `KSecant.PR`, `KSecant.spinPR`: the real plane `P_ℝ ⊆ S_ℝ` and `Spin(V_ℝ)_P`.
* `iotaX`, `iotaXHat`: the embeddings of `S_X = ⋀• H¹(X)` and `S_X̂ = ⋀• H¹(X̂)` in `C(V)` as
  subalgebras (`H¹(X)` and `H¹(X̂)` are isotropic); `ptHatC = [pt_X̂] = f₁ ⋯ f_{2n} ∈ C(V)`.
* `varphi`: Chevalley's `φ : S ⊗ S → C(V)`, `φ(u ⊗ v) = u [pt_X̂] τ(v)` (2.2.5).
* `cliffordTopPiece F n W`: `⋀^{2n} W` regarded as a subspace of `C(V)` (products of `2n` vectors
  of `W`).

## Statements

* **Remark 2.2.5** (`remark2_2_5`, in the corrected form agreed with the project owner: the whole
  circle `cos θ + sin θ · I` in `ρ(Spin(V_ℝ)_P)`).
* Claims in the proof of Lemma 2.2.6 on `φ`: `m_varphi_tmul` (the footnote: `m ∘ φ` is
  `(-1)^n` times `s ⊗ t ↦ s ⊗ (t, ·)_S`) and `closure_varphi_SZ` (`φ` is onto `C(V)` over
  `ℤ`). The cited facts [Chevalley, III.3.1] (`φ ⊗ ℚ` is a `Spin(V_ℚ)`-equivariant isomorphism) and
  [Chevalley, III.3.2] (`φ(ℓ̃ ⊗ ℓ̃) = ⋀^{2n} W ⊆ C(V)`) are in
  `WeilClasses.External.Chevalley.Sec2_2`.
* **Lemma 2.2.6** (`lemma2_2_6`, `lemma2_2_6_V01`) and the decomposition
  `W_{i,ℂ} = (W_{i,ℂ} ∩ V^{1,0}) ⊕ (W_{i,ℂ} ∩ V^{0,1})` proved on the way (`lemma2_2_6_decomp`,
  used in §2.4: "`I` commutes with `f`, by Lemma 2.2.6").

The Hodge structure on `C(V)` induced by `m : C(V) ≅ End(S)`, used in the paper's proof, is not
formalized as such; in the model it is the action of the circle `exp(t I)` on `V` and of its lift
`exp(-t D_J)` on `S` (`D_J` the derivation of `⋀• H¹(X)` extending `J`; `I = I_{V_ℝ}` acts on the
summand `H¹(X)` by `-J`).
-/

@[expose] public section

namespace WeilClasses

open CliffordAlgebra TensorProduct

/-! ## Chevalley's isomorphism `φ` (2.2.5) -/

section Varphi

variable (F : Type*) [Field F] [CharZero F] (n : ℕ)

/-- The top exterior power `⋀^{2n} W` of a subspace `W ⊆ V_F`, "considered as a one-dimensional
subspace of `C(V)`" (proof of Lemma 2.2.6): the span of the products `w₁ ⋯ w_{2n}` in `C(V_F)` of
`2n` vectors of `W`. For `W` isotropic of dimension `2n` it is a line. -/
noncomputable def cliffordTopPiece (W : Submodule F (V F n)) : Submodule F (C F n) :=
  Submodule.span F
    {x | ∃ w : Fin (2 * n) → V F n, (∀ i, w i ∈ W) ∧ x = (List.ofFn fun i => ι (Q F n) (w i)).prod}

omit [CharZero F] in
theorem varphi_tmul (u v : S F n) :
    varphi F n (u ⊗ₜ v) = iotaX F n u * ptHatC F n * iotaX F n (tau F n v) := by
  simp [varphi]

/-- The footnote in the proof of Lemma 2.2.6: `m ∘ φ : S ⊗ S → End(S)` is `(-1)^n` times the map
`s ⊗ t ↦ s ⊗ (t, ·)_S`, i.e. `m_{φ(s ⊗ t)}(x) = (-1)^n (t, x)_S s`. -/
theorem m_varphi_tmul (s t x : S F n) :
    m F n (varphi F n (s ⊗ₜ t)) x = ((-1) ^ n * mukai F n t x) • s := by
  sorry

/-- "**`φ` is an isomorphism over `ℤ`**" (proof of Lemma 2.2.6, with its footnote and
[GLO, Prop. 3.2.1(e)]): `φ` maps `S ⊗_ℤ S` onto the integral Clifford algebra `C(V)`, i.e. the
additive group generated by the `φ(s ⊗ t)`, `s, t ∈ S = H*(X, ℤ)`, is `CZ n`. (Injectivity holds
over `ℚ`, [Chevalley, III.3.1].) -/
theorem closure_varphi_SZ (n : ℕ) :
    AddSubgroup.closure
        {x | ∃ s ∈ SZ n, ∃ t ∈ SZ n, x = varphi ℚ n (s ⊗ₜ t)} =
      (CZ n).toAddSubgroup := by
  sorry

end Varphi

namespace KSecant

variable {n : ℕ} {d : ℚ} (P : KSecant n d)

/-! ## Complexifications and real points -/

/-! ## Remark 2.2.5 -/

/-- **Remark 2.2.5** (`remark-P-is-contained-in-the-Hodge-ring-if-I-is-in-image-of-Spin-V-P`): if the
whole circle group `{cos θ + sin θ · I}` generated by the complex structure `I` of `X × X̂` lies in
`ρ(Spin(V_ℝ)_P)`, then `P` is contained in the Hodge ring of `X`. Standing hypotheses at this point:
`P` non-isotropic, `K` imaginary quadratic.

Correction of the paper (agreed with the project owner; REPORT.md): the paper assumes only
`I ∈ ρ(Spin(V_ℝ)_P)`, and then the remark is false. Counterexample (`n = 2`, `d = 1`): `X = E × E`
with `E = ℂ/ℤ[i]`, `u₁ = dz₁ ∧ dz₂`, so that `P_ℂ = H^{2,0} ⊕ H^{0,2}`; the lift `g₀` of `I` acts on
`H^{p,q}` by `i^{p-q}`, so `-g₀ ∈ Spin(V_ℝ)_P` and `ρ(-g₀) = I`, but `P` meets the Hodge ring in `0`.
The whole circle is what the argument of the paper (proof of Lemma 4.0.3(2)) provides and uses. -/
theorem _root_.WeilClasses.remark2_2_5 (hd : 0 < d) (hP : ¬ P.IsIsotropic)
    (J : Module.End ℝ (H1 ℝ n)) (hJ : IsComplexStructure J)
    (hI : ∀ θ : ℝ, ∃ g ∈ P.spinPR,
      (rho ℝ n g).toLinearMap = Real.cos θ • (1 : Module.End ℝ (V ℝ n)) +
        Real.sin θ • productStructure n J) :
    P.Pℚ ≤ hodgeRingX n J := by
  sorry

/-! ## Lemma 2.2.6 -/

/-- **Lemma 2.2.6** (`lemma-decomposition-into-4-direct-summands`): if `P` is contained in the Hodge
ring of `X`, then `W₁^{1,0} := W_{1,ℂ} ∩ V^{1,0}` and `W₂^{1,0} := W_{2,ℂ} ∩ V^{1,0}` are both
`n`-dimensional. Here `V^{1,0}` is the `i`-eigenspace of the complex structure of `X × X̂`. Standing
hypotheses: `P` non-isotropic (not used by the proof), `K` imaginary quadratic. -/
theorem _root_.WeilClasses.lemma2_2_6 (hd : 0 < d) (hP : ¬ P.IsIsotropic)
    (J : Module.End ℝ (H1 ℝ n)) (hJ : IsComplexStructure J) (hPJ : P.Pℚ ≤ hodgeRingX n J) :
    Module.finrank ℂ (P.W₁ℂ ⊓ V10 n (productStructure n J) : Submodule ℂ (V ℂ n)) = n ∧
      Module.finrank ℂ (P.W₂ℂ ⊓ V10 n (productStructure n J) : Submodule ℂ (V ℂ n)) = n := by
  sorry

/-- **Lemma 2.2.6** (`lemma-decomposition-into-4-direct-summands`), the equivalent form: if `P` is
contained in the Hodge ring, then `W₁^{0,1} := W_{1,ℂ} ∩ V^{0,1}` and
`W₂^{0,1} := W_{2,ℂ} ∩ V^{0,1}` are both `n`-dimensional. -/
theorem _root_.WeilClasses.lemma2_2_6_V01 (hd : 0 < d) (hP : ¬ P.IsIsotropic)
    (J : Module.End ℝ (H1 ℝ n)) (hJ : IsComplexStructure J) (hPJ : P.Pℚ ≤ hodgeRingX n J) :
    Module.finrank ℂ (P.W₁ℂ ⊓ V01 n (productStructure n J) : Submodule ℂ (V ℂ n)) = n ∧
      Module.finrank ℂ (P.W₂ℂ ⊓ V01 n (productStructure n J) : Submodule ℂ (V ℂ n)) = n := by
  sorry

/-- The decomposition proved in Lemma 2.2.6 (`lemma-decomposition-into-4-direct-summands`): if `P`
is contained in the Hodge ring, then `W_{i,ℂ}` is invariant under the circle action of the Hodge
structure, so `W_{i,ℂ} = (W_{i,ℂ} ∩ V^{1,0}) ⊕ (W_{i,ℂ} ∩ V^{0,1})` for `i = 1, 2`. Used in §2.4
("`I` commutes with `f`, by Lemma 2.2.6") and in §§3–4. -/
theorem _root_.WeilClasses.lemma2_2_6_decomp (hd : 0 < d) (hP : ¬ P.IsIsotropic)
    (J : Module.End ℝ (H1 ℝ n)) (hJ : IsComplexStructure J) (hPJ : P.Pℚ ≤ hodgeRingX n J) :
    P.W₁ℂ =
        P.W₁ℂ ⊓ V10 n (productStructure n J) ⊔ P.W₁ℂ ⊓ V01 n (productStructure n J) ∧
      P.W₂ℂ =
        P.W₂ℂ ⊓ V10 n (productStructure n J) ⊔ P.W₂ℂ ⊓ V01 n (productStructure n J) := by
  sorry

end KSecant

end WeilClasses
