module

public import WeilClasses.Defs

/-!
# The imaginary quadratic field `K = ℚ(√-d)` inside `ℂ`

The paper fixes a positive rational (later integer) `d`, sets `K := ℚ(√-d)`, and chooses the square
root `√-d := √d · e^{iπ/2}` of argument `π/2` (§2.4, before (2.4.1)). We realize `K` as the subfield
of `ℂ` generated by `√-d` (`WeilClasses.Kd`, in `WeilClasses.Defs`), whose elements are the numbers
`a + b √-d` with `a, b ∈ ℚ` (`Kd.mem_iff`); its embedding into `ℂ` is the inclusion, so the paper's
choice of square root is built in. The Galois involution `σ` of `K/ℚ` (§2.2) is complex
conjugation (`Kd.σ`), and the norm `Nm` (the field norm of `K/ℚ`, `WeilClasses.Kd.Nm`) is
`Nm(λ) = λ σ(λ)` (`Kd.coe_Nm`).
-/

@[expose] public section

namespace WeilClasses

open Complex

theorem sqrtNeg_sq {d : ℚ} (hd : 0 ≤ d) : sqrtNeg d ^ 2 = -(d : ℂ) := by
  sorry

namespace Kd

variable (d : ℚ)

/-- `K = ℚ(√-d)` consists of the numbers `a + b √-d`, `a, b ∈ ℚ` (for `d ≤ 0`, `√-d = 0` and
`K = ℚ`). -/
theorem mem_iff {z : ℂ} : z ∈ Kd d ↔ ∃ a b : ℚ, z = a + b * WeilClasses.sqrtNeg d := by
  sorry

theorem conj_mem {z : ℂ} (hz : z ∈ Kd d) : (starRingEnd ℂ) z ∈ Kd d := by
  sorry

/-- The Galois involution `σ` of `K/ℚ`: the restriction of complex conjugation (paper, §2.2). -/
noncomputable def σ : Kd d ≃+* Kd d where
  toFun z := ⟨(starRingEnd ℂ) z, conj_mem d z.2⟩
  invFun z := ⟨(starRingEnd ℂ) z, conj_mem d z.2⟩
  left_inv z := Subtype.ext (by simp)
  right_inv z := Subtype.ext (by simp)
  map_mul' x y := Subtype.ext (by simp)
  map_add' x y := Subtype.ext (by simp)

@[simp]
theorem coe_σ (z : Kd d) : ((σ d z : Kd d) : ℂ) = (starRingEnd ℂ) z := rfl

/-- `Nm(λ) = λ σ(λ)` (paper, §2.2), for `d > 0` (`[K : ℚ] = 2`). -/
theorem coe_Nm {d : ℚ} (hd : 0 < d) (z : Kd d) : ((Nm d z : ℚ) : ℂ) = (z : ℂ) * (starRingEnd ℂ) z := by
  sorry

/-- The norm group `Nm(K^×) ⊆ ℚ^×` (paper, §1.1 and (2.2.3)). -/
def normGroup : Set ℚ := {q | ∃ z : Kd d, z ≠ 0 ∧ Nm d z = q}

end Kd

noncomputable example (d : ℚ) : Algebra (Kd d) ℂ := inferInstance
noncomputable example (d : ℚ) : Algebra ℚ (Kd d) := inferInstance
example (d : ℚ) : IsScalarTower ℚ (Kd d) ℂ := inferInstance
example : IsScalarTower ℚ ℝ ℂ := inferInstance

end WeilClasses
