module

public import WeilClasses.Spinor.Defs

/-!
# `H*(X̂)`, the embeddings of `H*(X)` and `H*(X̂)` in `C(V)`, and Chevalley's `φ` (2.2.5)

* `SHat F n = ⋀• H¹(X̂, F)` (`H¹(X̂) = H¹(X)*`), its basis `f_K`, `[pt_X̂] = f₁ ∧ ⋯ ∧ f_{2n}` and
  `∫_X̂`; `ExtV F n = ⋀• V_F`.
* The summands `H¹(X)` and `H¹(X̂)` of `V` are isotropic, so their exterior algebras embed in `C(V)`
  as subalgebras: `iotaX : S_X → C(V)` (`w ↦ ι(0, w)`) and `iotaXHat : S_X̂ → C(V)`; `[pt_X̂] ∈ C(V)`
  (`ptHatC`).
* Chevalley's map `φ : S ⊗ S → C(V)`, `φ(u ⊗ v) = u [pt_X̂] τ(v)` (`varphi`, (2.2.5), in the proof
  of Lemma 2.2.6; [Chevalley, III.3.1]).
-/

@[expose] public section

namespace WeilClasses

open CliffordAlgebra TensorProduct

section Defs

variable (F : Type*) [Field F] [CharZero F] (n : ℕ)

/-- The basis `f_K = f_{i₁} ∧ ⋯ ∧ f_{i_k}` (`i₁ < ⋯ < i_k`) of `H*(X̂, F)`, built from the basis
`f_i` of `H¹(X̂, F)` dual to `e_i`. -/
noncomputable def basisSHat : Module.Basis (Finset (Fin (2 * n))) F (SHat F n) :=
  ((Pi.basisFun F (Fin (2 * n))).dualBasis).ExteriorAlgebra

/-- `[pt_X̂] = f₁ ∧ ⋯ ∧ f_{2n} ∈ H^{2n}(X̂, F)` (proof of Lemma 2.3.2). -/
noncomputable def ptHat : SHat F n := basisSHat F n Finset.univ

/-- Integration `∫_X̂ : H*(X̂, F) → F`: the coefficient of `[pt_X̂] = f₁ ∧ ⋯ ∧ f_{2n}`. -/
noncomputable def integralHat : SHat F n →ₗ[F] F := (basisSHat F n).coord Finset.univ

omit [CharZero F] in
theorem ι_inr_mul_self (w : H1 F n) :
    CliffordAlgebra.ι (Q F n) (0, w) * CliffordAlgebra.ι (Q F n) (0, w) = 0 := by
  rw [CliffordAlgebra.ι_sq_scalar]
  simp

omit [CharZero F] in
theorem ι_inl_mul_self (θ : Module.Dual F (H1 F n)) :
    CliffordAlgebra.ι (Q F n) (θ, 0) * CliffordAlgebra.ι (Q F n) (θ, 0) = 0 := by
  rw [CliffordAlgebra.ι_sq_scalar]
  simp

/-- The embedding `S_X = ⋀• H¹(X) → C(V)` as the subalgebra generated by the isotropic subspace
`H¹(X) = {(0, w)}` of `V` (proof of Lemma 2.2.6): exterior products go to Clifford products. -/
noncomputable def iotaX : S F n →ₐ[F] C F n :=
  ExteriorAlgebra.lift F
    ⟨(CliffordAlgebra.ι (Q F n)) ∘ₗ LinearMap.inr F (Module.Dual F (H1 F n)) (H1 F n),
      fun w => ι_inr_mul_self F n w⟩

/-- The embedding `S_X̂ = ⋀• H¹(X̂) → C(V)` (`θ ↦ ι(θ, 0)`; `H¹(X̂)` is isotropic). -/
noncomputable def iotaXHat : SHat F n →ₐ[F] C F n :=
  ExteriorAlgebra.lift F
    ⟨(CliffordAlgebra.ι (Q F n)) ∘ₗ LinearMap.inl F (Module.Dual F (H1 F n)) (H1 F n),
      fun θ => ι_inl_mul_self F n θ⟩

/-- `[pt_X̂] = f₁ ⋯ f_{2n}` regarded as an element of `C(V)`. -/
noncomputable def ptHatC : C F n := iotaXHat F n (ptHat F n)

/-- **(2.2.5)** (`eq-Chevalley-varphi`) Chevalley's map [Chevalley, III.3.1] `φ : S ⊗ S → C(V)`,
`φ(u ⊗ v) = u [pt_X̂] τ(v)`, for `u, v ∈ S_X ⊆ C(V)` (`τ` the main anti-automorphism of `S_X`). -/
noncomputable def varphi : S F n ⊗[F] S F n →ₗ[F] C F n :=
  TensorProduct.lift (((LinearMap.mul F (C F n)).compl₂ ((iotaX F n).toLinearMap ∘ₗ tau F n)) ∘ₗ
      (LinearMap.mulRight F (ptHatC F n)) ∘ₗ (iotaX F n).toLinearMap)

end Defs

end WeilClasses
