module

public import WeilClasses.Spinor.Defs

/-!
# Integral structures (paper §1.2 and §2.1)

The paper works with the lattices `H¹(X, ℤ)`, `V = H¹(X, ℤ) ⊕ H¹(X̂, ℤ)`, `S = H*(X, ℤ)` and
`⋀• V = H*(X × X̂, ℤ)`, the integral Clifford algebra `C(V)` and the integral spin group
`Spin(V) = {x ∈ C(V)^even : x x* = 1, x V x* ⊆ V}`. We realize them inside the rational objects:

* `H1Z`, `VZ`, `SZ`, `ExtZ`: the vectors with integer coordinates in the standard bases;
* `CZ`: the subring of `C(V_ℚ)` generated by `V` (the image of the integral Clifford algebra);
* `SpinZ`: the elements of `Spin(V_ℚ)` lying in `CZ` and preserving `V` under `ρ`, which is the
  paper's integral `Spin(V)` since `C(V) → C(V_ℚ)` is injective (`V` is free).
-/

@[expose] public section

namespace WeilClasses

open CliffordAlgebra

variable (n : ℕ)

/-- `H¹(X, ℤ) ⊆ H¹(X, ℚ)`: the vectors with integer coordinates. -/
def H1Z : AddSubgroup (H1 ℚ n) where
  carrier := {w | ∀ i, ∃ z : ℤ, w i = z}
  add_mem' := by sorry
  zero_mem' := fun i => ⟨0, by simp⟩
  neg_mem' := by sorry

/-- The lattice `V = H¹(X̂, ℤ) ⊕ H¹(X, ℤ) ⊆ V_ℚ` (1.2.1). -/
def VZ : AddSubgroup (V ℚ n) where
  carrier := {v | (∀ i, ∃ z : ℤ, v.1 (e ℚ n i) = z) ∧ ∀ i, ∃ z : ℤ, v.2 i = z}
  add_mem' := by sorry
  zero_mem' := ⟨fun i => ⟨0, by simp⟩, fun i => ⟨0, by simp⟩⟩
  neg_mem' := by sorry

/-- `S = H*(X, ℤ) ⊆ S_ℚ`: integer coefficients in the basis `e_K`. -/
noncomputable def SZ : AddSubgroup (S ℚ n) where
  carrier := {s | ∀ K, ∃ z : ℤ, (basisS ℚ n).repr s K = z}
  add_mem' := by sorry
  zero_mem' := fun K => ⟨0, by simp⟩
  neg_mem' := by sorry

/-- `H*(X × X̂, ℤ) = ⋀• V ⊆ ⋀• V_ℚ`: integer coefficients in `basisExt`. -/
noncomputable def ExtZ : AddSubgroup (ExteriorAlgebra ℚ (V ℚ n)) where
  carrier := {α | ∀ K, ∃ z : ℤ, (basisExt ℚ n).repr α K = z}
  add_mem' := by sorry
  zero_mem' := fun K => ⟨0, by simp⟩
  neg_mem' := by sorry

/-- The integral Clifford algebra `C(V)`, as the subring of `C(V_ℚ)` generated by `V`. -/
noncomputable def CZ : Subring (C ℚ n) :=
  Subring.closure (CliffordAlgebra.ι (Q ℚ n) '' (VZ n : Set (V ℚ n)))

/-- The integral spin group `Spin(V) = {x ∈ C(V)^even : x x* = 1, x V x* ⊆ V}` (§2.1), inside
`Spin(V_ℚ)`. -/
noncomputable def SpinZ : Subgroup (Spin ℚ n) where
  carrier := {g | (g : C ℚ n) ∈ CZ n ∧ ∀ v ∈ VZ n, rho ℚ n g v ∈ VZ n}
  one_mem' := by sorry
  mul_mem' := by sorry
  inv_mem' := by sorry

end WeilClasses
