module

public import WeilClasses.Spinor.Defs

/-!
# Integral structures (paper §1.2 and §2.1)

The paper works with the lattices `H¹(X, ℤ)`, `V = H¹(X, ℤ) ⊕ H¹(X̂, ℤ)`, `S = H*(X, ℤ)` and
`⋀• V = H*(X × X̂, ℤ)`, the integral Clifford algebra `C(V)` and the integral spin group
`Spin(V) = {x ∈ C(V)^even : x x* = 1, x V x* ⊆ V}`. We realize them inside the rational objects:

* `H1Z`, `VZ`, `SZ`, `ExtZ`: the vectors with integer coordinates in the standard bases;
* `CZ`: the subring of `C(V_ℚ)` generated by `V` (the image of the integral Clifford algebra);
* `SpinZ`: the elements of `Spin(V_ℚ)` lying in `CZ` and preserving `V` under `ρ`, which is the
  paper's integral `Spin(V)` since `C(V) → C(V_ℚ)` is injective (`V` is free).
-/

@[expose] public section

namespace WeilClasses

open CliffordAlgebra

variable (n : ℕ)

/-- `H¹(X, ℤ) ⊆ H¹(X, ℚ)`: the vectors with integer coordinates. -/
def H1Z : AddSubgroup (H1 ℚ n) where
  carrier := {w | ∀ i, ∃ z : ℤ, w i = z}
  add_mem' := by
    rintro a b ha hb i
    obtain ⟨x, hx⟩ := ha i
    obtain ⟨y, hy⟩ := hb i
    exact ⟨x + y, by simp [hx, hy]⟩
  zero_mem' := fun i => ⟨0, by simp⟩
  neg_mem' := by
    rintro a ha i
    obtain ⟨x, hx⟩ := ha i
    exact ⟨-x, by simp [hx]⟩

/-- The lattice `V = H¹(X̂, ℤ) ⊕ H¹(X, ℤ) ⊆ V_ℚ` (1.2.1). -/
def VZ : AddSubgroup (V ℚ n) where
  carrier := {v | (∀ i, ∃ z : ℤ, v.1 (e ℚ n i) = z) ∧ ∀ i, ∃ z : ℤ, v.2 i = z}
  add_mem' := by
    rintro a b ⟨ha₁, ha₂⟩ ⟨hb₁, hb₂⟩
    refine ⟨fun i => ?_, fun i => ?_⟩
    · obtain ⟨x, hx⟩ := ha₁ i
      obtain ⟨y, hy⟩ := hb₁ i
      exact ⟨x + y, by simp [hx, hy]⟩
    · obtain ⟨x, hx⟩ := ha₂ i
      obtain ⟨y, hy⟩ := hb₂ i
      exact ⟨x + y, by simp [hx, hy]⟩
  zero_mem' := ⟨fun i => ⟨0, by simp⟩, fun i => ⟨0, by simp⟩⟩
  neg_mem' := by
    rintro a ⟨ha₁, ha₂⟩
    refine ⟨fun i => ?_, fun i => ?_⟩
    · obtain ⟨x, hx⟩ := ha₁ i
      exact ⟨-x, by simp [hx]⟩
    · obtain ⟨x, hx⟩ := ha₂ i
      exact ⟨-x, by simp [hx]⟩

/-- `S = H*(X, ℤ) ⊆ S_ℚ`: integer coefficients in the basis `e_K`. -/
noncomputable def SZ : AddSubgroup (S ℚ n) where
  carrier := {s | ∀ K, ∃ z : ℤ, (basisS ℚ n).repr s K = z}
  add_mem' := by
    rintro a b ha hb K
    obtain ⟨x, hx⟩ := ha K
    obtain ⟨y, hy⟩ := hb K
    exact ⟨x + y, by simp [hx, hy]⟩
  zero_mem' := fun K => ⟨0, by simp⟩
  neg_mem' := by
    rintro a ha K
    obtain ⟨x, hx⟩ := ha K
    exact ⟨-x, by simp [hx]⟩

/-- `H*(X × X̂, ℤ) = ⋀• V ⊆ ⋀• V_ℚ`: integer coefficients in `basisExt`. -/
noncomputable def ExtZ : AddSubgroup (ExteriorAlgebra ℚ (V ℚ n)) where
  carrier := {α | ∀ K, ∃ z : ℤ, (basisExt ℚ n).repr α K = z}
  add_mem' := by
    rintro a b ha hb K
    obtain ⟨x, hx⟩ := ha K
    obtain ⟨y, hy⟩ := hb K
    exact ⟨x + y, by simp [hx, hy]⟩
  zero_mem' := fun K => ⟨0, by simp⟩
  neg_mem' := by
    rintro a ha K
    obtain ⟨x, hx⟩ := ha K
    exact ⟨-x, by simp [hx]⟩

/-- The integral Clifford algebra `C(V)`, as the subring of `C(V_ℚ)` generated by `V`. -/
noncomputable def CZ : Subring (C ℚ n) :=
  Subring.closure (CliffordAlgebra.ι (Q ℚ n) '' (VZ n : Set (V ℚ n)))

/-- `C(V)` is stable under the conjugation `x ↦ x*` (`v* = -v` on `V`, and `*` reverses
products). -/
private theorem fnd_star_mem_CZ {x : C ℚ n} (hx : x ∈ CZ n) : star x ∈ CZ n := by
  induction hx using Subring.closure_induction with
  | mem x hx =>
      obtain ⟨v, hv, rfl⟩ := hx
      rw [star_ι]
      exact Subring.neg_mem _ (Subring.subset_closure ⟨v, hv, rfl⟩)
  | zero => simp
  | one => simp
  | add x y _ _ hx hy => simpa only [star_add] using Subring.add_mem _ hx hy
  | neg x _ hx => simpa only [star_neg] using Subring.neg_mem _ hx
  | mul x y _ _ hx hy => simpa only [star_mul] using Subring.mul_mem _ hy hx

/-- The pairing (1.2.2): `((θ₁,w₁),(θ₂,w₂))_V = θ₁(w₂) + θ₂(w₁)`. -/
private theorem fnd_pairing_apply (v y : V ℚ n) : pairing ℚ n v y = v.1 y.2 + y.1 v.2 := by
  simp only [pairing, QuadraticMap.polarBilin_apply_apply, QuadraticMap.polar, Q,
    QuadraticForm.dualProd_apply, Prod.fst_add, Prod.snd_add, map_add, LinearMap.add_apply]
  ring

/-- `θ(w) = Σᵢ θ(eᵢ) wᵢ`. -/
private theorem fnd_dual_apply (θ : Module.Dual ℚ (H1 ℚ n)) (w : H1 ℚ n) :
    θ w = ∑ i, θ (e ℚ n i) * w i := by
  conv_lhs => rw [show w = ∑ i, w i • e ℚ n i by ext j; simp [e, Pi.single_apply]]
  simp [map_sum, mul_comm]

/-- The pairing (1.2.2) is integral on `V`. -/
private theorem fnd_pairing_VZ {v y : V ℚ n} (hv : v ∈ VZ n) (hy : y ∈ VZ n) :
    ∃ z : ℤ, pairing ℚ n v y = z := by
  have hR : pairing ℚ n v y ∈ (Int.castRingHom ℚ).range := by
    rw [fnd_pairing_apply, fnd_dual_apply, fnd_dual_apply]
    refine Subring.add_mem _ (Subring.sum_mem _ fun i _ => Subring.mul_mem _ ?_ ?_)
      (Subring.sum_mem _ fun i _ => Subring.mul_mem _ ?_ ?_)
    · obtain ⟨z, hz⟩ := hv.1 i; exact ⟨z, by simp [hz]⟩
    · obtain ⟨z, hz⟩ := hy.2 i; exact ⟨z, by simp [hz]⟩
    · obtain ⟨z, hz⟩ := hy.1 i; exact ⟨z, by simp [hz]⟩
    · obtain ⟨z, hz⟩ := hv.2 i; exact ⟨z, by simp [hz]⟩
  obtain ⟨z, hz⟩ := hR
  exact ⟨z, by simpa using hz.symm⟩

/-- `V` is unimodular: a vector of `V_ℚ` with integral pairing against `V` lies in `V`. -/
private theorem fnd_mem_VZ_of_pairing (u : V ℚ n)
    (h : ∀ y ∈ VZ n, ∃ z : ℤ, pairing ℚ n u y = z) : u ∈ VZ n := by
  refine ⟨fun i => ?_, fun i => ?_⟩
  · have hmem : ((0, e ℚ n i) : V ℚ n) ∈ VZ n := by
      refine ⟨fun j => ⟨0, by simp⟩, fun j => ?_⟩
      by_cases hij : j = i
      · exact ⟨1, by simp [e, hij]⟩
      · exact ⟨0, by simp [e, hij]⟩
    obtain ⟨z, hz⟩ := h _ hmem
    exact ⟨z, by simpa [fnd_pairing_apply] using hz⟩
  · have hmem : ((f ℚ n i, 0) : V ℚ n) ∈ VZ n := by
      refine ⟨fun j => ?_, fun j => ⟨0, by simp⟩⟩
      by_cases hij : i = j
      · exact ⟨1, by simp [e, f, hij]⟩
      · exact ⟨0, by simp [e, f, hij]⟩
    obtain ⟨z, hz⟩ := h _ hmem
    exact ⟨z, by simpa [fnd_pairing_apply, f] using hz⟩

/-- `ρ(g)` is an isometry of the pairing (1.2.2). -/
private theorem fnd_pairing_rho (g : Spin ℚ n) (a b : V ℚ n) :
    pairing ℚ n (rho ℚ n g a) (rho ℚ n g b) = pairing ℚ n a b := by
  simp only [pairing, QuadraticMap.polarBilin_apply_apply, QuadraticMap.polar, rho, ← map_add,
    spinVectorAction_map_app]

/-- If `ρ(g)` preserves the unimodular lattice `V`, so does `ρ(g)⁻¹ = ρ(g⁻¹)`: for `v ∈ V` and
`y ∈ V`, `(ρ(g⁻¹) v, y) = (v, ρ(g) y) ∈ ℤ`. -/
private theorem fnd_rho_inv_mem_VZ (g : Spin ℚ n) (hg : ∀ v ∈ VZ n, rho ℚ n g v ∈ VZ n)
    (v : V ℚ n) (hv : v ∈ VZ n) : rho ℚ n g⁻¹ v ∈ VZ n := by
  apply fnd_mem_VZ_of_pairing
  intro y hy
  have hv' : rho ℚ n g (rho ℚ n g⁻¹ v) = v := by
    have := spinVectorAction_mul (Q ℚ n) g g⁻¹
    rw [mul_inv_cancel, spinVectorAction_one] at this
    have h2 := congrArg (fun φ : V ℚ n ≃ₗ[ℚ] V ℚ n => φ v) this
    simpa [rho] using h2.symm
  rw [← fnd_pairing_rho n g, hv']
  exact fnd_pairing_VZ n hv (hg y hy)

/-- The integral spin group `Spin(V) = {x ∈ C(V)^even : x x* = 1, x V x* ⊆ V}` (§2.1), inside
`Spin(V_ℚ)`. -/
noncomputable def SpinZ : Subgroup (Spin ℚ n) where
  carrier := {g | (g : C ℚ n) ∈ CZ n ∧ ∀ v ∈ VZ n, rho ℚ n g v ∈ VZ n}
  one_mem' := by
    refine ⟨Subring.one_mem _, fun v hv => ?_⟩
    simpa [rho] using hv
  mul_mem' := by
    rintro g h ⟨hg, hgV⟩ ⟨hh, hhV⟩
    refine ⟨Subring.mul_mem _ hg hh, fun v hv => ?_⟩
    have : rho ℚ n (g * h) v = rho ℚ n g (rho ℚ n h v) := by simp [rho]
    rw [this]
    exact hgV _ (hhV _ hv)
  inv_mem' := by
    rintro g ⟨hg, hgV⟩
    exact ⟨fnd_star_mem_CZ n hg, fnd_rho_inv_mem_VZ n g hgV⟩

end WeilClasses
