module

public import WeilClasses.Spinor.Embeddings
public import Mathlib.RingTheory.Nilpotent.Exp
public import Mathlib.Algebra.Algebra.Rat

/-!
# Contraction with a class, and `⋀• H¹(X)` inside the Clifford algebra (paper §2.4)

Two constructions used in §2.4 of the paper (TeX lines 1310–1345):

* `WeilClasses.contractOne`: for `ξ ∈ S_F = H*(X, F)`, the map `H¹(X, F)* → H¹(X, F)`,
  `y ↦ y ⌋ ξ` in degree one. For a class `Θ ∈ H²(X)` it is the paper's map
  `θ : H¹(X, ℚ)* → H¹(X, ℚ)` "contraction with `Θ`" (2.4.3). We contract from the left
  (`D_y = contractLeft y`, the operator of the spin representation (2.1.2)); this is the order for
  which (2.4.4), (2.4.6) and the formula `H((0, yᵢ), (0, yⱼ)) = d √-d Θ(yᵢ, yⱼ)` in the proof of
  Lemma 3.1.3 hold, with `Θ(y, y') := ⟪Θ, y ∧ y'⟫ = y'(θ(y))` (`WeilClasses.eval2`).
* `WeilClasses.iotaX`: the embedding of `⋀• H¹(X, F)` in `C(V_F)` as the subalgebra generated by the
  isotropic summand `H¹(X, F) = 0 × H¹(X, F)` of `V_F` (`w₁ ∧ ⋯ ∧ w_k ↦ w₁ ⋯ w_k`). The spin
  representation of `j(s)` is cup product with `s` (`WeilClasses.m_jH`). The element `exp(u)` of
  `Spin(V_K)` of §2.4 (`u = √-d Θ`) is `IsNilpotent.exp (j u)`.
-/

@[expose] public section

namespace WeilClasses

open CliffordAlgebra

variable (F : Type*) [Field F] [CharZero F] (n : ℕ)

/-- For `ξ ∈ S_F = H*(X, F)`, the linear map `H¹(X, F)* → H¹(X, F)` sending `y` to (the
coordinates in the basis `eᵢ` of) the degree-one part of the contraction `D_y ξ = y ⌋ ξ`. For
`ξ = Θ ∈ H²(X, ℚ)` this is the paper's `θ` (2.4.3), and for `ξ = bcS ℚ F n Θ` its `F`-linear
extension. -/
noncomputable def contractOne (ξ : S F n) : Module.Dual F (H1 F n) →ₗ[F] H1 F n :=
  (LinearMap.pi fun i => (basisS F n).coord {i}) ∘ₗ (D F n).flip ξ

/-- For `ξ ∈ H²(X, F)`, `D_y ξ` is the vector `contractOne ξ y` of degree one. -/
theorem ι_contractOne (ξ : S F n) (hξ : ξ ∈ ⋀[F]^2 (H1 F n)) (y : Module.Dual F (H1 F n)) :
    ExteriorAlgebra.ι F (contractOne F n ξ y) = D F n y ξ := by
  sorry

/-- The spin representation of `j(s)` is cup product with `s`: `m(j(s)) = s ∪ (·)`. -/
theorem m_jH (s : S F n) : m F n (iotaX F n s) = LinearMap.mulLeft F s := by
  sorry

/-- For `u ∈ H²(X, F)`, the spin representation of `exp(j(u))` is cup product with `exp(u)`
(§2.4, before (2.4.4): "cup product with `exp(u)` … corresponding to the spin representation image of
an element `exp(u)`"). -/
theorem m_exp_jH (u : S F n) (hu : u ∈ ⋀[F]^2 (H1 F n)) :
    m F n (IsNilpotent.exp (iotaX F n u)) = LinearMap.mulLeft F (IsNilpotent.exp u) := by
  sorry

end WeilClasses
